/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    public static void main(String[] args) {
        // Instantiate the bmp image
        Bitmap bitmap = new Bitmap(args[0]);

        // Transform image
        if (args.length > 2)
        switch(args[2]) {
            case "crazy":
                bitmap.crazy();
                break;
            case "light":
                bitmap.light();
                break;
            case "invert":
                bitmap.invert();
                break;
            case "vflip":
                bitmap.vflip();
                break;
            case "hflip":
                bitmap.hflip();
                break;
        }

        // Write out image
        bitmap.save(args[1]);
    }
}
