/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public static void main(String[] args) {

        // Read in the bmp file
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("yellow_tiger_cat.bmp"));
            System.out.println("Read file good!");
        } catch (IOException e) {
            System.out.println("Failed to open image");
            System.out.println(e);
        }

        // Instantiate the bmp image
        Bitmap bitmap = new Bitmap(img);

        bitmap.darken();

        try {
            boolean success;
            success = ImageIO.write(bitmap.getImageData(), "gif", new File("image.bmp"));
            System.out.println("Success status " + success);
        } catch (IOException e) {
            System.out.println("ERROR SAVING!");
            System.out.println(e);
        }
    }
}
